# Created by: %%FULLNAME%% <%%EMAIL%%>
# $FreeBSD$

PORTNAME=	%%PORTNAME%%
DISTVERSION=
CATEGORIES=
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	%%EMAIL%%
COMMENT=

USES=	cran:auto-plist

.include <bsd.port.mk>
